---
driver:
  name: vagrant

platforms:
  - name: centos-7.2
  - name: centos-6.7
  - name: centos-5.11
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: amazon
    driver:
      name: dokken
      image: dokken/amazonlinux
    transport:
      name: dokken
    provisioner:
      name: dokken

suites:
  - name: default
    run_list:
      - recipe[clamav_test]
  - name: all_options_enabled
    run_list:
      - recipe[clamav_test]
    attributes:
      clamav:
        clamd:
          enabled: true
          log_file: false
          log_syslog: yes
          log_facility: LOG_LOCAL7
        freshclam:
          enabled: true
          update_log_file: false
          log_syslog: yes
          log_facility: LOG_LOCAL7
          rhel_cron_disable: false
        dev_package: true
        scan:
          script:
            enable: true
          minimal:
            enable: true
          full:
            enable: true
